config/routes.rb
Rails.application.routes.draw do
  resources :responsibles
  root to: "tasks#index"

  resources :tasks
  get "not_found", to: "errors#not_found"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/responsible.rb
class Responsible < ApplicationRecord
  has_many :tasks, dependent: :destroy

  validates_presence_of :name
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :responsible

  validates_presence_of :title, :description, :due_date, :responsible
  validate :due_date_in_future

  STATUSES = %w(todo doing done trash).freeze
  PRIORITIES = %w(low medium high urgent).freeze

  enum status: {
    todo:  0,
    doing: 1,
    done:  2, 
    trash: 3
  }

  enum priority: {
    low:    0,
    medium: 1,
    high:   2,
    urgent: 3
  }

  def due_date_in_future
    return if due_date && due_date > DateTime.now
    return unless due_date_changed?

    errors.add(:due_date, "must be in the future")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: :not_found
  end
end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
  before_action :set_responsible, only: [:show, :edit, :update, :destroy]

  # GET /responsibles
  # GET /responsibles.json
  def index
    @responsibles = Responsible.all
  end

  # GET /responsibles/1
  # GET /responsibles/1.json
  def show
  end

  # GET /responsibles/new
  def new
    @responsible = Responsible.new
  end

  # GET /responsibles/1/edit
  def edit
  end

  # POST /responsibles
  # POST /responsibles.json
  def create
    @responsible = Responsible.new(responsible_params)

    respond_to do |format|
      if @responsible.save
        format.html { redirect_to @responsible, notice: 'Responsible was successfully created.' }
        format.json { render :show, status: :created, location: @responsible }
      else
        format.html { render :new }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibles/1
  # PATCH/PUT /responsibles/1.json
  def update
    respond_to do |format|
      if @responsible.update(responsible_params)
        format.html { redirect_to @responsible, notice: 'Responsible was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsible }
      else
        format.html { render :edit }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibles/1
  # DELETE /responsibles/1.json
  def destroy
    @responsible.destroy
    respond_to do |format|
      format.html { redirect_to responsibles_url, notice: 'Responsible was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsible
      @responsible = Responsible.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      redirect_to '/not_found'
    end

    # Only allow a list of trusted parameters through.
    def responsible_params
      params.require(:responsible).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])

    rescue ActiveRecord::RecordNotFound 
      redirect_to '/not_found'
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :priority, :status, :responsible_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav_bar' %>
    <div class="container mx-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/responsibles/_form.html.erb
<%= form_with(model: responsible, local: true) do |form| %>
  <% if responsible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(responsible.errors.count, "error") %> prohibited this responsible from being saved:</h2>

      <ul>
      <% responsible.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <span class="text-danger">*</span>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="float-right">
    <%= link_to 'Back', responsibles_path, class: "mr-3" %>
    <%= form.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/responsibles/edit.html.erb
<h1>Editing Responsible</h1>

<%= render 'form', responsible: @responsible %>

app/views/responsibles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responsibles</h1>

<table class="table mt-4">
  <thead class="thead-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibles.each do |responsible| %>
      <tr>
        <td scope="row"><%= responsible.name %></td>
        <td scope="row"><%= link_to 'Show', responsible %></td>
        <td scope="row"><%= link_to 'Edit', edit_responsible_path(responsible) %></td>
        <td scope="row"><%= link_to 'Destroy', responsible, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Responsible', new_responsible_path, class: "btn btn-primary" %>

app/views/responsibles/new.html.erb
<div class="w-50 mx-auto">
  <h1 class="text-center pt-4">New Responsible</h1>

  <%= render 'form', responsible: @responsible %>
</div>

app/views/responsibles/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @responsible.name %></h2>

<div class="mt-5">
  <%= link_to 'Back', responsibles_path, class: "mr-2" %>
  <%= link_to 'Edit', edit_responsible_path(@responsible), class: "btn btn-primary mr-2" %>
  <%= link_to 'Delete',  @responsible, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mr-2" %>
</div>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to tasks_path, class: "navbar-brand" do %>
    <%= image_tag('task_icon.png', size: "40") %>
    <span class="pl-2">Task Manager</span>   
	<% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Tasks", tasks_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Responsibles", responsibles_path, class: "nav-link" %>
      </li>
    </ul>
  </div>

	<%= link_to "Create Task", new_task_path, class: "btn btn-outline-secondary" %>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <span class="text-danger">*</span>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <span class="text-danger">*</span>
    <%= form.text_field :description, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <div>
      <%= form.label :due_date %>
      <span class="text-danger">*</span>
    </div>
    <%= form.datetime_select :due_date, {}, {class: "form-control d-inline", style: "width: auto;", required: true} %>
  </div>

  <div class="form-group">
    <%= form.label :priority %>
    <span class="text-danger">*</span>
    <%= form.select :priority, Task::PRIORITIES, {}, {class: "form-control", required: true}  %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <span class="text-danger">*</span>
    <%= form.select :status, Task::STATUSES, {}, {class: "form-control", required: true}  %>
  </div>

  <div class="form-group">
    <%= form.label :responsible %>
    <span class="text-danger">*</span>
    <%= form.select :responsible_id, Responsible.order(:name).collect { |r| [ r.name, r.id ] }, {}, {class: "form-control", required: true}  %>
  </div>

  <div class="float-right">
    <%= link_to 'Back', tasks_path, class: "mr-3" %>
    <%= form.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="w-50 mx-auto">
  <h1 class="text-center pt-4">Editing Task</h1>
  <%= render 'form', task: @task %>
</div>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<div class="row mt-4">
  <%= render 'tasks/index/status_column', title: 'Todo', tasks: @tasks.where(status: 'todo') %>
  <%= render 'tasks/index/status_column', title: 'Doing', tasks: @tasks.where(status: 'doing') %>
  <%= render 'tasks/index/status_column', title: 'Done', tasks: @tasks.where(status: 'done') %>
  <%= render 'tasks/index/status_column', title: 'Trash', tasks: @tasks.where(status: 'trash') %>
</div>

app/views/tasks/index/_card.html.erb
<div class="card mb-2">
  <div class="card-body">
    <div class="mb-1">
      <%= link_to task.title, task_path(task.id), class: "card-title", style: "font-size: 20px;" %>
    </div>

    <h6 class="card-subtitle mb-2 text-muted">
      <%= task.priority %>
      | <%= task.due_date.strftime("%d/%m/%y %H:%M") %>
    </h6>

    <p class="card-text" style="font-size: 14px;"><%= task.description %></p>

    <div>
      <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-fill align-middle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
      </svg>
      <span class="align-middle">
        <%= link_to task.responsible.name, responsible_path(task.responsible.id) %>
      </span>
    </div>
  </div>
</div>

app/views/tasks/index/_status_column.html.erb
<div class="col-3">
  <div class="border rounded p-2 bg-light" style="max-height: 100vh; overflow: auto;">
    <h2><%= title %></h2>

    <% if tasks.count == 0 %>
      <p class="text-muted">No tasks for now</p>
    <% end %>

    <% tasks.each do |task| %> 
      <%= render 'tasks/index/card', task: task %>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="w-50 mx-auto">
  <h1 class="text-center pt-4">New Task</h1>
  <%= render 'form', task: @task %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @task.title %></h2>

<div class="mt-3">
  <p>
    <strong>Description:</strong>
    <%= @task.description %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= @task.due_date.strftime("%d/%m/%y %H:%M") %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= @task.priority %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @task.status %>
  </p>

  <p>
    <strong>Responsible:</strong>
    <%= @task.responsible.name %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= @task.created_at.strftime("%d/%m/%y %H:%M") %>
  </p>
</div>

<div class="mt-5">
  <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-primary mr-2" %>
  <%= link_to 'Delete',  @task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mr-2" %>
  <%= link_to 'Back', tasks_path %>
</div>